version: '3.8'

services:
  db1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: replication_db
      MYSQL_USER: repluser
      MYSQL_PASSWORD: replpassword
    ports:
      - "33061:3306"
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin=mysql-bin --binlog-format=ROW --gtid-mode=ON --enforce-gtid-consistency=ON --master-info-repository=TABLE --relay-log-info-repository=TABLE --transaction-write-set-extraction=XXHASH64 --binlog-checksum=NONE --relay-log=db1-relay-bin --log-slave-updates=ON

  db2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: replication_db
      MYSQL_USER: repluser
      MYSQL_PASSWORD: replpassword
    ports:
      - "33062:3306"
    command: --default-authentication-plugin=mysql_native_password --server-id=2 --log-bin=mysql-bin --binlog-format=ROW --gtid-mode=ON --enforce-gtid-consistency=ON --master-info-repository=TABLE --relay-log-info-repository=TABLE --transaction-write-set-extraction=XXHASH64 --binlog-checksum=NONE --relay-log=db2-relay-bin --log-slave-updates=ON

  setup:
    image: mysql:8.0
    depends_on:
      - db1
      - db2
    volumes:
      - ./setup-master-master-replication.sql:/docker-entrypoint-initdb.d/setup-master-master-replication.sql
    entrypoint: ['bash', '-c', 'sleep 15 && mysql -h db1 -u root -prootpassword < /docker-entrypoint-initdb.d/setup-master-master-replication.sql && echo "Replication setup completed"']
